spring:
  application:
    name: item-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wukaichun1/sp-config
          searchPaths: config
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
